---
baseurl: "/"
permalink: "/:title/"
title: Snipcart
snipcart_js: https://cdn.snipcart.com/scripts/2.0/snipcart.js
snipcart_css: https://cdn.snipcart.com/themes/2.0/base/snipcart.min.css
snipcart_api_key: YzViMTVmZWMtOTQ1My00MTYxLTkxNzgtZmUyNmRkZjE3OTM4NjM2NjMyMjE0OTE3MDA1MjMx
logos:
  light:
    optimized: "/images/logo-healthy-pleasures.svg"
    fallback: "/images/logo-healthy-pleasures.png"
  dark:
    optimized: "/images/logo-healthy-pleasures.svg"
    fallback: "/images/logo-healthy-pleasures.png"
palette: default
palettes:
  default: "light"
    sass:
      default: "#FFFFFF"
      light: "#F0F0F0"
      medium: "#6B797A"
      dark: "#384647"
      active: "#88DD9B"
      active_light: "#C0FDB6"
      active_medium: "#5C9174"
      active_dark: "#547567"
      dark_grey: "#273132"
      light_grey: "#6B797A"
      bg_image_primary_optimized: "/images/header.webp"
      bg_image_primary_fallback: "/images/header.jpg"
      bg_image_secondary_optimized: "/images/leaf-light-grey.svg"
      bg_image_secondary_fallback: "/images/leaf-light-grey.svg"
      bg_image_product_optimized: "/images/leaf.svg"
      bg_image_product_fallback: "/images/leaf.svg"
      bg_image_cart_optimized: "/images/cart-bg.webp"
      bg_image_cart_fallback: "/images/header.jpg"
sass:
  style: nested
  precision: 10
plugins:
- jekyll-menus
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ssg-build.sh
- LICENSE.md
- README.md
- netlify.toml
- stackbit-build.sh
- stackbit-pull.js
collections:
  posts:
    permalink: "/posts/:title/"
