---
label: Product
hide_body: true
fields:
- type: text
  name: id
  label: ID 100g
  description: Un número único para identificar el producto.
- name: id2
  type: text
  config:
    required: false
  label: ID 265g
  description: Un número único para identificar el producto.
- name: id3
  type: text
  config:
    required: false
  label: ID 1kg
  description: Un número único para identificar el producto.
- type: text
  name: title
  label: Title
- type: text
  name: description
  label: Description
- type: text
  name: price1
  label: Precio - 100g
- name: price2
  type: text
  config:
    required: false
  label: Precio - 265g
- name: price3
  type: text
  config:
    required: false
  label: Precio - 1kg
- type: field_group
  name: images
  label: Images
  fields:
  - type: field_group
    name: default
    label: Default
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  - type: field_group
    name: featured
    label: Featured
    fields:
    - type: field_group
      name: thumbnail
      label: Thumbnail
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
    - type: field_group
      name: original
      label: Original
      fields:
      - type: file
        name: optimized
        label: Optimized (WEBP or similar)
      - type: file
        name: fallback
        label: Fallback (JPG or PNG)
  description: 'Imágenes en formato cuadrado. Max 500x500. '
- type: select
  name: category
  label: Category
  config:
    source:
      type: simple
    options:
    - almendra
    - maní
    - marañón
- type: boolean
  name: featured
  label: Featured
  description: 'Selecciónalo si quieres que salga en Best-sellers. '
- type: select
  name: section
  label: Section
  config:
    source:
      type: custom
    options:
    - Store
    - About
    - Home
- type: text
  name: layout
  label: Layout
  hidden: true
  default: product
  config:
    required: true
pages:
- products/mantequilla-de-maní-con-proteína.md
- products/mantequilla-de-maní-con-coco.md
- products/mantequilla-de-marañón-clásica.md
- products/mantequilla-de-marañón-con-proteína.md
- products/mantequilla-de-marañón-con-chocolate.md
- products/mantequilla-de-marañón-con-coco.md
- products/mantequilla-de-almendras-clásica.md
- products/mantequilla-de-almendras-con-proteína.md
- products/mantequilla-de-almendras-con-coco.md
- products/mantequilla-de-almendras-con-chocolate.md
- products/mantequilla-de-maní-con-chocolate.md
- products/mantequilla-de-maní-clásica.md
- products/test-img.md
